export const ELEMENTS = {
  fire:    { id: 'fire',    name: 'Огонь',    color: '#FF4500', glow: 'rgba(255,69,0,0.4)',  desc: 'Бушующее пламя', starter: true },
  water:   { id: 'water',   name: 'Вода',     color: '#1E90FF', glow: 'rgba(30,144,255,0.4)', desc: 'Чистая вода', starter: true },
  earth:   { id: 'earth',   name: 'Земля',    color: '#8B4513', glow: 'rgba(139,69,19,0.4)',  desc: 'Плодородная почва', starter: true },
  air:     { id: 'air',     name: 'Воздух',   color: '#C8D8E8', glow: 'rgba(200,216,232,0.3)',desc: 'Невидимый ветер', starter: true },
  void:    { id: 'void',    name: 'Пустота',  color: '#7B3FAF', glow: 'rgba(123,63,175,0.5)',  desc: 'Абсолютная пустота', starter: true },
  steam:   { id: 'steam',   name: 'Пар',      color: '#C0C8D0', glow: 'rgba(192,200,208,0.3)',desc: 'Густой белый пар' },
  hotSteam:{ id: 'hotSteam',name: 'Горячий Пар', color: '#FF6B35', glow: 'rgba(255,107,53,0.4)', desc: 'Обжигающие испарения' },
  wetSteam:{ id: 'wetSteam',name: 'Влажный Пар', color: '#89CFF0', glow: 'rgba(137,207,240,0.4)',desc: 'Тяжёлая водяная взвесь' },
  lava:    { id: 'lava',    name: 'Лава',     color: '#FF6600', glow: 'rgba(255,102,0,0.5)',  desc: 'Раскалённая магма' },
  magma:   { id: 'magma',   name: 'Магма',    color: '#E25822', glow: 'rgba(226,88,34,0.5)',  desc: 'Густой огненный расплав' },
  scoria:  { id: 'scoria',  name: 'Шлак',     color: '#4A3728', glow: 'rgba(74,55,40,0.4)',   desc: 'Остывшие обломки' },
  mud:     { id: 'mud',     name: 'Грязь',    color: '#6B4226', glow: 'rgba(107,66,38,0.4)',  desc: 'Мокрые отложения' },
  sludge:  { id: 'sludge',  name: 'Тина',     color: '#3B5E2B', glow: 'rgba(59,94,43,0.4)',   desc: 'Гнилая болотная жижа' },
  ice:     { id: 'ice',     name: 'Лёд',      color: '#88DDFF', glow: 'rgba(136,221,255,0.4)',desc: 'Хрустальный холод' },
  mist:    { id: 'mist',    name: 'Туман',    color: '#A0B4C8', glow: 'rgba(160,180,200,0.3)',desc: 'Плотная дымка' },
  dust:    { id: 'dust',    name: 'Пыль',     color: '#C8B896', glow: 'rgba(200,184,150,0.3)',desc: 'Мелкодисперсная взвесь' },
  lightning: { id: 'lightning', name: 'Молния', color: '#FFD700', glow: 'rgba(255,215,0,0.5)',desc: 'Небесный разряд' },
  light:   { id: 'light',   name: 'Свет',     color: '#FFFACD', glow: 'rgba(255,250,205,0.4)',desc: 'Ослепительное сияние' },
  shadow:  { id: 'shadow',  name: 'Тень',     color: '#1A1A3E', glow: 'rgba(26,26,62,0.5)',  desc: 'Сгусток тьмы' },
  metal:   { id: 'metal',   name: 'Металл',   color: '#708090', glow: 'rgba(112,128,144,0.4)',desc: 'Холодная сталь' },
  ether:   { id: 'ether',   name: 'Эфир',     color: '#9370DB', glow: 'rgba(147,112,219,0.4)',desc: 'Тонкая материя' },
  ash:     { id: 'ash',     name: 'Пепел',    color: '#4A4A5A', glow: 'rgba(74,74,90,0.3)',   desc: 'Останки огня' },
  stone:   { id: 'stone',   name: 'Камень',   color: '#808080', glow: 'rgba(128,128,128,0.3)',desc: 'Твёрдая порода' },
  crystal: { id: 'crystal', name: 'Кристалл', color: '#FF69B4', glow: 'rgba(255,105,180,0.4)',desc: 'Сверкающий самоцвет' },
  storm:   { id: 'storm',   name: 'Буря',     color: '#4682B4', glow: 'rgba(70,130,180,0.4)', desc: 'Разъярённая стихия' },
  acid:    { id: 'acid',    name: 'Кислота',  color: '#7CFC00', glow: 'rgba(124,252,0,0.4)',  desc: 'Едкая субстанция' },
  plasma:  { id: 'plasma',  name: 'Плазма',   color: '#FF00FF', glow: 'rgba(255,0,255,0.4)',  desc: 'Чистая энергия' },
  geyser:  { id: 'geyser',  name: 'Гейзер',   color: '#00CED1', glow: 'rgba(0,206,209,0.4)',  desc: 'Кипящий источник' },
  sand:    { id: 'sand',    name: 'Песок',    color: '#F4A460', glow: 'rgba(244,164,96,0.3)', desc: 'Сыпучие крупицы' },
  glass:   { id: 'glass',   name: 'Стекло',   color: '#87CEEB', glow: 'rgba(135,206,235,0.3)',desc: 'Прозрачный сплав' },
  brick:   { id: 'brick',   name: 'Кирпич',   color: '#B22222', glow: 'rgba(178,34,34,0.4)',  desc: 'Обожжённая глина' },
  poison:  { id: 'poison',  name: 'Яд',       color: '#8B008B', glow: 'rgba(139,0,139,0.4)',  desc: 'Смертельный яд' },
  life:    { id: 'life',    name: 'Жизнь',    color: '#32CD32', glow: 'rgba(50,205,50,0.4)',  desc: 'Живительная искра' },
  death:   { id: 'death',   name: 'Смерть',   color: '#2F4F4F', glow: 'rgba(47,79,79,0.4)',   desc: 'Вечный покой' },
  essence: { id: 'essence', name: 'Эссенция', color: '#FFD700', glow: 'rgba(255,215,0,0.5)',  desc: 'Первозданная сила' },
  prism:   { id: 'prism',   name: 'Призма',   color: '#E8A0FF', glow: 'rgba(232,160,255,0.4)', desc: 'Преломлённый свет' },
  rust:    { id: 'rust',    name: 'Ржавчина', color: '#A0522D', glow: 'rgba(160,82,45,0.3)',   desc: 'Окисленный металл' },
  wood:    { id: 'wood',    name: 'Древесина',color: '#8B5E3C', glow: 'rgba(139,94,60,0.4)',   desc: 'Твёрдая кора' },
  clay:    { id: 'clay',    name: 'Глина',    color: '#C4A882', glow: 'rgba(196,168,130,0.3)', desc: 'Мягкая порода' },
  ceramic: { id: 'ceramic', name: 'Керамика', color: '#D2691E', glow: 'rgba(210,105,30,0.4)',  desc: 'Обожжённое изделие' },
  swamp:   { id: 'swamp',   name: 'Болото',   color: '#2E4A1E', glow: 'rgba(46,74,30,0.4)',    desc: 'Гнилая трясина' },
  forest:  { id: 'forest',  name: 'Лес',      color: '#228B22', glow: 'rgba(34,139,34,0.4)',   desc: 'Древняя чаща' },
  flower:  { id: 'flower',  name: 'Цветок',   color: '#FF69B4', glow: 'rgba(255,105,180,0.4)', desc: 'Нежный бутон' },
  pearl:   { id: 'pearl',   name: 'Жемчуг',   color: '#F5F5DC', glow: 'rgba(245,245,220,0.3)', desc: 'Морское сокровище' },
  steel:   { id: 'steel',   name: 'Сталь',    color: '#A0A8B0', glow: 'rgba(160,168,176,0.4)', desc: 'Крепкий сплав' },
  blade:   { id: 'blade',   name: 'Клинок',   color: '#C0C0C0', glow: 'rgba(192,192,192,0.4)', desc: 'Острое лезвие' },
  crown:   { id: 'crown',   name: 'Корона',   color: '#FFD700', glow: 'rgba(255,215,0,0.5)',   desc: 'Символ власти' },
  rune:    { id: 'rune',    name: 'Руна',     color: '#00CED1', glow: 'rgba(0,206,209,0.4)',   desc: 'Древний символ' },
  potion:  { id: 'potion',  name: 'Зелье',    color: '#00FF7F', glow: 'rgba(0,255,127,0.4)',   desc: 'Мистический эликсир' },
  ghost:   { id: 'ghost',   name: 'Призрак',  color: '#D8BFD8', glow: 'rgba(216,191,216,0.3)', desc: 'Бесплотный дух' },
  golem:   { id: 'golem',   name: 'Голем',    color: '#696969', glow: 'rgba(105,105,105,0.3)', desc: 'Оживший камень' },
  hurricane: { id: 'hurricane', name: 'Ураган', color: '#4A6FA5', glow: 'rgba(74,111,165,0.4)',desc: 'Свирепый ветер' },
  star:    { id: 'star',    name: 'Звезда',   color: '#FFFACD', glow: 'rgba(255,250,205,0.4)', desc: 'Небесное тело' },
  nova:    { id: 'nova',    name: 'Нова',     color: '#FF1493', glow: 'rgba(255,20,147,0.4)',  desc: 'Вспышка сверхновой' },
  meteor:  { id: 'meteor',  name: 'Метеор',   color: '#B22222', glow: 'rgba(178,34,34,0.4)',   desc: 'Падающая звезда' },
  obsidian: { id: 'obsidian', name: 'Обсидиан', color: '#1C1C2E', glow: 'rgba(28,28,46,0.5)', desc: 'Вулканическое стекло' },
  amulet:  { id: 'amulet',  name: 'Амулет',   color: '#FFD700', glow: 'rgba(255,215,0,0.5)',   desc: 'Магический артефакт' },
  phoenix: { id: 'phoenix', name: 'Феникс',   color: '#FF6347', glow: 'rgba(255,99,71,0.5)',   desc: 'Бессмертная птица' },
  fossil:  { id: 'fossil',  name: 'Окаменелость', color: '#8B7355', glow: 'rgba(139,115,85,0.3)',desc: 'Древнее окаменение' },
  abyss:   { id: 'abyss',   name: 'Бездна',   color: '#0A0022', glow: 'rgba(10,0,34,0.5)',    desc: 'Бесконечная тьма' },
  chimera: { id: 'chimera', name: 'Химера',   color: '#FF00FF', glow: 'rgba(255,0,255,0.5)',   desc: 'Слияние сущностей' },
  inferno:  { id: 'inferno',  name: 'Инферно',   color: '#FF2200', glow: 'rgba(255,34,0,0.5)',  desc: 'Пекло' },
  spring:   { id: 'spring',   name: 'Родник',    color: '#00BFFF', glow: 'rgba(0,191,255,0.4)', desc: 'Чистый источник' },
  mountain: { id: 'mountain', name: 'Гора',      color: '#6B5B4F', glow: 'rgba(107,91,79,0.4)', desc: 'Каменная гряда' },
  gale:     { id: 'gale',     name: 'Шквал',     color: '#A8C8E8', glow: 'rgba(168,200,232,0.3)',desc: 'Порывистый ветер' },
  rift:     { id: 'rift',     name: 'Разлом',    color: '#4A0080', glow: 'rgba(74,0,128,0.5)',  desc: 'Трещина в реальности' },
  moss:     { id: 'moss',     name: 'Мох',       color: '#5B8C3E', glow: 'rgba(91,140,62,0.4)', desc: 'Мягкий зелёный покров' },
  coral:    { id: 'coral',    name: 'Коралл',    color: '#FF6F8C', glow: 'rgba(255,111,140,0.4)',desc: 'Морское образование' },
  amber:    { id: 'amber',    name: 'Янтарь',    color: '#FFBF00', glow: 'rgba(255,191,0,0.4)', desc: 'Окаменевшая смола' },
  mirage:   { id: 'mirage',   name: 'Мираж',     color: '#E0D8C0', glow: 'rgba(224,216,192,0.3)',desc: 'Обманчивое видение' },
  eclipse:  { id: 'eclipse',  name: 'Затмение',  color: '#1A0033', glow: 'rgba(26,0,51,0.5)',   desc: 'Слияние света и тьмы' },
  thunder:  { id: 'thunder',  name: 'Гром',      color: '#8A6F00', glow: 'rgba(138,111,0,0.4)', desc: 'Раскатистый гул' },
  diamond:  { id: 'diamond',  name: 'Алмаз',     color: '#B0E0E6', glow: 'rgba(176,224,230,0.4)',desc: 'Твёрдый кристалл' },
  mirror:   { id: 'mirror',   name: 'Зеркало',   color: '#C0C8D8', glow: 'rgba(192,200,216,0.3)',desc: 'Отражающая поверхность' },
  siren:    { id: 'siren',    name: 'Сирена',    color: '#2E8B57', glow: 'rgba(46,139,87,0.4)', desc: 'Зачаровывающий голос' },
  clockwork:{ id: 'clockwork',name: 'Механизм',  color: '#8B7D3C', glow: 'rgba(139,125,60,0.4)', desc: 'Сложное устройство' },
  frost:    { id: 'frost',    name: 'Иней',      color: '#B0E0E6', glow: 'rgba(176,224,230,0.3)',desc: 'Морозный налёт' },
  bubble:   { id: 'bubble',   name: 'Пузырь',    color: '#87CEEB', glow: 'rgba(135,206,235,0.4)',desc: 'Лёгкий мыльный шар' },
  echo:     { id: 'echo',     name: 'Эхо',       color: '#9CA8B8', glow: 'rgba(156,168,184,0.3)',desc: 'Отражённый звук' },
  vine:     { id: 'vine',     name: 'Лоза',      color: '#3B7A3B', glow: 'rgba(59,122,59,0.4)', desc: 'Вьющееся растение' },
  root:     { id: 'root',     name: 'Корень',    color: '#5C4033', glow: 'rgba(92,64,51,0.4)',  desc: 'Подземная сеть' },
  mushroom: { id: 'mushroom', name: 'Гриб',      color: '#C4A882', glow: 'rgba(196,168,130,0.4)',desc: 'Споровое тело' },
  seed:     { id: 'seed',     name: 'Семя',      color: '#8B7355', glow: 'rgba(139,115,85,0.3)', desc: 'Зародыш жизни' },
  gold:     { id: 'gold',     name: 'Золото',    color: '#FFD700', glow: 'rgba(255,215,0,0.5)', desc: 'Благородный металл' },
  silver:   { id: 'silver',   name: 'Серебро',   color: '#C0C0C0', glow: 'rgba(192,192,192,0.4)',desc: 'Лунный металл' },
  iron:     { id: 'iron',     name: 'Железо',    color: '#8B7D6B', glow: 'rgba(139,125,107,0.4)',desc: 'Крепкий рудный металл' },
  scroll:   { id: 'scroll',   name: 'Свиток',    color: '#F5DEB3', glow: 'rgba(245,222,179,0.3)',desc: 'Древний манускрипт' },
  lantern:  { id: 'lantern',  name: 'Фонарь',    color: '#DAA520', glow: 'rgba(218,165,32,0.4)', desc: 'Источник света' },
  key:      { id: 'key',      name: 'Ключ',      color: '#B8860B', glow: 'rgba(184,134,11,0.4)', desc: 'Отпирает тайны' },
  shield:   { id: 'shield',   name: 'Щит',       color: '#6B5B4F', glow: 'rgba(107,91,79,0.4)', desc: 'Надёжная защита' },
  wand:     { id: 'wand',     name: 'Жезл',      color: '#8B5CF6', glow: 'rgba(139,92,246,0.4)', desc: 'Проводник магии' },
  curse:    { id: 'curse',    name: 'Проклятие', color: '#4A0033', glow: 'rgba(74,0,51,0.5)',   desc: 'Тёмное заклятие' },
  fairy:    { id: 'fairy',    name: 'Фея',       color: '#FFB7C5', glow: 'rgba(255,183,197,0.4)',desc: 'Крылатый дух' },
  phantom:  { id: 'phantom',  name: 'Фантом',    color: '#A0A0C0', glow: 'rgba(160,160,192,0.3)',desc: 'Бестелесная тень' },
  philosophersStone: { id: 'philosophersStone', name: 'Философский Камень', color: '#C9A227', glow: 'rgba(201,162,39,0.4)', desc: 'Венец алхимии' },
  moon:     { id: 'moon',     name: 'Луна',      color: '#F5F5DC', glow: 'rgba(245,245,220,0.3)',desc: 'Ночное светило' },
  sun:      { id: 'sun',      name: 'Солнце',    color: '#FF8C00', glow: 'rgba(255,140,0,0.5)', desc: 'Дневное светило' },
  galaxy:   { id: 'galaxy',   name: 'Галактика', color: '#9370DB', glow: 'rgba(147,112,219,0.4)',desc: 'Звёздный вихрь' },
  elixir:   { id: 'elixir',   name: 'Эликсир',   color: '#00FF7F', glow: 'rgba(0,255,127,0.4)', desc: 'Чистая субстанция' },
  catalyst: { id: 'catalyst', name: 'Катализатор',color: '#FFD700', glow: 'rgba(255,215,0,0.5)',desc: 'Ускоритель реакций' },
  salt:     { id: 'salt',     name: 'Соль',      color: '#F5F5F5', glow: 'rgba(245,245,245,0.3)',desc: 'Кристаллический осадок' },
};

export const ELEMENT_IDS = Object.keys(ELEMENTS);
export const STARTER_IDS = ELEMENT_IDS.filter(id => ELEMENTS[id].starter);

export const CATEGORIES = {
  starter: { label: '🔥 Стихии', color: '#ffd700' },
  state:   { label: '🌊 Состояния', color: '#88ddff' },
  nature:  { label: '🌿 Природа', color: '#32cd32' },
  metal:   { label: '⛰ Металлы', color: '#708090' },
  artifact:{ label: '🏺 Артефакты', color: '#d2691e' },
  magic:   { label: '🔮 Магия', color: '#9370db' },
  cosmos:  { label: '🌌 Космос', color: '#4a6fa5' },
  alchemy: { label: '⚗ Алхимия', color: '#7cfc00' },
  legendary: { label: '👑 Легендарное', color: '#C9A227' },
};

export const ELEMENT_CATS = {
  fire:'starter', water:'starter', earth:'starter', air:'starter', void:'starter',
  steam:'state', hotSteam:'state', wetSteam:'state', ice:'state', mist:'state',
  dust:'state', ash:'state', lava:'state', magma:'state', scoria:'state', mud:'state', sludge:'state', storm:'state',
  wood:'nature', forest:'nature', flower:'nature', life:'nature', swamp:'nature', poison:'nature',
  metal:'metal', steel:'metal', blade:'metal', rust:'metal', stone:'metal', crystal:'metal',
  glass:'artifact', brick:'artifact', ceramic:'artifact', clay:'artifact', crown:'artifact',
  amulet:'artifact', rune:'artifact', prism:'artifact',
  light:'magic', shadow:'magic', essence:'magic', ghost:'magic', golem:'magic',
  phoenix:'magic', chimera:'magic', abyss:'magic',
  ether:'cosmos', star:'cosmos', nova:'cosmos', meteor:'cosmos',
  potion:'alchemy', acid:'alchemy', pearl:'alchemy', sand:'alchemy', obsidian:'alchemy',
  fossil:'alchemy', geyser:'alchemy', hurricane:'alchemy', lightning:'alchemy',
  plasma:'alchemy', death:'alchemy',
  inferno:'state', spring:'nature', mountain:'nature', gale:'state', rift:'magic',
  moss:'nature', coral:'nature', amber:'alchemy', mirage:'magic', eclipse:'cosmos',
  thunder:'state', diamond:'metal', mirror:'artifact', siren:'magic', clockwork:'artifact',
  frost:'state', bubble:'state', echo:'state', vine:'nature', root:'nature',
  mushroom:'nature', seed:'nature', gold:'metal', silver:'metal', iron:'metal',
  scroll:'artifact', lantern:'artifact', key:'artifact', shield:'artifact',
  wand:'magic', curse:'magic', fairy:'magic', phantom:'magic',
  moon:'cosmos', sun:'cosmos', galaxy:'cosmos',
  elixir:'alchemy', catalyst:'alchemy', salt:'alchemy',
  philosophersStone:'legendary',
};

export const RECIPES = [
  { inputs: [{ id: 'fire', a: 1 }, { id: 'water', a: 1 }], output: 'steam' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'earth', a: 1 }], output: 'lava' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'earth', a: 1 }], output: 'mud' },
  { inputs: [{ id: 'water', a: 2 }, { id: 'air', a: 1 }], output: 'ice', ratio: { id: 'water', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'water', a: 1 }, { id: 'air', a: 1 }], output: 'mist' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'air', a: 1 }], output: 'dust' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'air', a: 1 }], output: 'lightning' },
  { inputs: [{ id: 'void', a: 1 }, { id: 'fire', a: 1 }], output: 'light' },
  { inputs: [{ id: 'void', a: 1 }, { id: 'water', a: 1 }], output: 'shadow' },
  { inputs: [{ id: 'void', a: 1 }, { id: 'earth', a: 1 }], output: 'metal' },
  { inputs: [{ id: 'void', a: 1 }, { id: 'air', a: 1 }], output: 'ether' },
  { inputs: [{ id: 'fire', a: 2 }, { id: 'water', a: 1 }], output: 'hotSteam', ratio: { id: 'fire', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'water', a: 2 }], output: 'wetSteam', ratio: { id: 'water', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'water', a: 2 }, { id: 'earth', a: 1 }], output: 'sludge', ratio: { id: 'water', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'fire', a: 2 }, { id: 'earth', a: 1 }], output: 'magma', ratio: { id: 'fire', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'earth', a: 2 }], output: 'scoria', ratio: { id: 'earth', min: 1.5, max: Infinity } },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'dust', a: 1 }], output: 'ash' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'lava', a: 1 }], output: 'stone' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'lightning', a: 1 }], output: 'crystal' },
  { inputs: [{ id: 'air', a: 1 }, { id: 'lightning', a: 1 }], output: 'storm' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'lightning', a: 1 }], output: 'acid' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'lightning', a: 1 }], output: 'plasma' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'lava', a: 1 }], output: 'geyser' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'dust', a: 1 }], output: 'sand' },
  { inputs: [{ id: 'air', a: 1 }, { id: 'dust', a: 1 }], output: 'sand' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'sand', a: 1 }], output: 'glass' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'mud', a: 1 }], output: 'brick' },
  { inputs: [{ id: 'mud', a: 1 }, { id: 'shadow', a: 1 }], output: 'poison' },
  { inputs: [{ id: 'light', a: 1 }, { id: 'water', a: 1 }], output: 'life' },
  { inputs: [{ id: 'shadow', a: 1 }, { id: 'void', a: 1 }], output: 'death' },
  { inputs: [{ id: 'light', a: 1 }, { id: 'shadow', a: 1 }], output: 'essence' },
  { inputs: [{ id: 'steam', a: 1 }, { id: 'air', a: 1 }], output: 'mist' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'stone', a: 1 }], output: 'lava' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'stone', a: 1 }], output: 'sand' },
  { inputs: [{ id: 'life', a: 1 }, { id: 'death', a: 1 }], output: 'essence' },
  { inputs: [{ id: 'ice', a: 1 }, { id: 'fire', a: 1 }], output: 'steam' },
  { inputs: [{ id: 'ash', a: 1 }, { id: 'water', a: 1 }], output: 'mud' },
  { inputs: [{ id: 'crystal', a: 1 }, { id: 'light', a: 1 }], output: 'prism' },
  { inputs: [{ id: 'metal', a: 1 }, { id: 'water', a: 1 }], output: 'rust' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'life', a: 1 }], output: 'wood' },
  { inputs: [{ id: 'mud', a: 1 }, { id: 'earth', a: 1 }], output: 'clay' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'clay', a: 1 }], output: 'ceramic' },
  { inputs: [{ id: 'mud', a: 1 }, { id: 'poison', a: 1 }], output: 'swamp' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'earth', a: 1 }], output: 'forest' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'light', a: 1 }], output: 'flower' },
  { inputs: [{ id: 'sand', a: 1 }, { id: 'light', a: 1 }], output: 'pearl' },
  { inputs: [{ id: 'metal', a: 1 }, { id: 'fire', a: 1 }], output: 'steel' },
  { inputs: [{ id: 'steel', a: 1 }, { id: 'stone', a: 1 }], output: 'blade' },
  { inputs: [{ id: 'metal', a: 1 }, { id: 'crystal', a: 1 }], output: 'crown' },
  { inputs: [{ id: 'stone', a: 1 }, { id: 'light', a: 1 }], output: 'rune' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'crystal', a: 1 }], output: 'potion' },
  { inputs: [{ id: 'shadow', a: 1 }, { id: 'ether', a: 1 }], output: 'ghost' },
  { inputs: [{ id: 'stone', a: 1 }, { id: 'life', a: 1 }], output: 'golem' },
  { inputs: [{ id: 'storm', a: 1 }, { id: 'water', a: 1 }], output: 'hurricane' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'shadow', a: 1 }], output: 'obsidian' },
  { inputs: [{ id: 'crystal', a: 1 }, { id: 'rune', a: 1 }], output: 'amulet' },
  { inputs: [{ id: 'death', a: 1 }, { id: 'stone', a: 1 }], output: 'fossil' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'life', a: 1 }, { id: 'light', a: 1 }], output: 'phoenix' },
  { inputs: [{ id: 'shadow', a: 1 }, { id: 'void', a: 1 }, { id: 'death', a: 1 }], output: 'abyss' },
  { inputs: [{ id: 'light', a: 1 }, { id: 'void', a: 1 }, { id: 'essence', a: 1 }], output: 'star' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'light', a: 1 }, { id: 'plasma', a: 1 }], output: 'nova' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'stone', a: 1 }, { id: 'void', a: 1 }], output: 'meteor' },
  { inputs: [{ id: 'storm', a: 1 }, { id: 'air', a: 1 }, { id: 'water', a: 1 }], output: 'hurricane' },
  { inputs: [{ id: 'mud', a: 1 }, { id: 'water', a: 1 }, { id: 'poison', a: 1 }], output: 'swamp' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'water', a: 1 }, { id: 'wood', a: 1 }], output: 'forest' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'water', a: 1 }, { id: 'light', a: 1 }], output: 'flower' },
  { inputs: [{ id: 'sand', a: 1 }, { id: 'water', a: 1 }, { id: 'light', a: 1 }], output: 'pearl' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'shadow', a: 1 }, { id: 'sand', a: 1 }], output: 'obsidian' },
  { inputs: [{ id: 'crystal', a: 1 }, { id: 'rune', a: 1 }, { id: 'essence', a: 1 }], output: 'amulet' },
  { inputs: [{ id: 'stone', a: 1 }, { id: 'life', a: 1 }, { id: 'earth', a: 1 }], output: 'golem' },
  { inputs: [{ id: 'death', a: 1 }, { id: 'stone', a: 1 }, { id: 'earth', a: 1 }], output: 'fossil' },
  { inputs: [{ id: 'hotSteam', a: 1 }, { id: 'stone', a: 1 }], output: 'geyser' },
  { inputs: [{ id: 'wetSteam', a: 1 }, { id: 'earth', a: 1 }], output: 'mud' },
  { inputs: [{ id: 'sludge', a: 1 }, { id: 'poison', a: 1 }], output: 'swamp' },
  { inputs: [{ id: 'magma', a: 1 }, { id: 'water', a: 1 }], output: 'obsidian' },
  { inputs: [{ id: 'scoria', a: 1 }, { id: 'water', a: 1 }], output: 'sand' },
  { inputs: [{ id: 'hotSteam', a: 1 }, { id: 'crystal', a: 1 }], output: 'prism' },
  { inputs: [{ id: 'wetSteam', a: 1 }, { id: 'flower', a: 1 }], output: 'pearl' },
  { inputs: [{ id: 'magma', a: 1 }, { id: 'air', a: 1 }], output: 'storm' },
  { inputs: [{ id: 'scoria', a: 1 }, { id: 'light', a: 1 }], output: 'glass' },
  { inputs: [{ id: 'sludge', a: 1 }, { id: 'shadow', a: 1 }], output: 'poison' },
  { inputs: [{ id: 'phoenix', a: 1 }, { id: 'ghost', a: 1 }, { id: 'golem', a: 1 }, { id: 'star', a: 1 }], output: 'chimera' },
  // Self-combinations
  { inputs: [{ id: 'fire', a: 2 }], output: 'inferno' },
  { inputs: [{ id: 'water', a: 2 }], output: 'spring' },
  { inputs: [{ id: 'earth', a: 2 }], output: 'mountain' },
  { inputs: [{ id: 'air', a: 2 }], output: 'gale' },
  { inputs: [{ id: 'void', a: 2 }], output: 'rift' },
  // New element recipes
  { inputs: [{ id: 'stone', a: 1 }, { id: 'life', a: 1 }], output: 'moss' },
  { inputs: [{ id: 'swamp', a: 1 }, { id: 'wood', a: 1 }], output: 'moss' },
  { inputs: [{ id: 'life', a: 1 }, { id: 'stone', a: 1 }, { id: 'water', a: 1 }], output: 'coral' },
  { inputs: [{ id: 'fossil', a: 1 }, { id: 'flower', a: 1 }], output: 'amber' },
  { inputs: [{ id: 'fossil', a: 1 }, { id: 'light', a: 1 }], output: 'amber' },
  { inputs: [{ id: 'void', a: 1 }, { id: 'light', a: 1 }], output: 'mirage' },
  { inputs: [{ id: 'dust', a: 1 }, { id: 'light', a: 1 }], output: 'mirage' },
  { inputs: [{ id: 'light', a: 1 }, { id: 'shadow', a: 1 }], output: 'eclipse' },
  { inputs: [{ id: 'essence', a: 1 }, { id: 'void', a: 1 }], output: 'eclipse' },
  { inputs: [{ id: 'lightning', a: 1 }, { id: 'storm', a: 1 }], output: 'thunder' },
  { inputs: [{ id: 'air', a: 1 }, { id: 'storm', a: 1 }], output: 'thunder' },
  { inputs: [{ id: 'crystal', a: 1 }, { id: 'stone', a: 1 }], output: 'diamond' },
  { inputs: [{ id: 'crystal', a: 1 }, { id: 'earth', a: 1 }], output: 'diamond' },
  { inputs: [{ id: 'glass', a: 1 }, { id: 'light', a: 1 }], output: 'mirror' },
  { inputs: [{ id: 'glass', a: 1 }, { id: 'essence', a: 1 }], output: 'mirror' },
  { inputs: [{ id: 'life', a: 1 }, { id: 'water', a: 1 }, { id: 'ghost', a: 1 }], output: 'siren' },
  { inputs: [{ id: 'metal', a: 1 }, { id: 'rune', a: 1 }], output: 'clockwork' },
  { inputs: [{ id: 'steel', a: 1 }, { id: 'rune', a: 1 }], output: 'clockwork' },
  // Cross-recipes for old elements
  { inputs: [{ id: 'ash', a: 1 }, { id: 'life', a: 1 }], output: 'phoenix' },
  { inputs: [{ id: 'brick', a: 1 }, { id: 'stone', a: 1 }], output: 'ceramic' },
  { inputs: [{ id: 'ceramic', a: 1 }, { id: 'water', a: 1 }], output: 'clay' },
  { inputs: [{ id: 'rust', a: 1 }, { id: 'acid', a: 1 }], output: 'poison' },
  { inputs: [{ id: 'rust', a: 1 }, { id: 'fire', a: 1 }], output: 'metal' },
  { inputs: [{ id: 'blade', a: 1 }, { id: 'rune', a: 1 }], output: 'clockwork' },
  { inputs: [{ id: 'crown', a: 1 }, { id: 'crystal', a: 1 }], output: 'amulet' },
  { inputs: [{ id: 'pearl', a: 1 }, { id: 'potion', a: 1 }], output: 'amber' },
  { inputs: [{ id: 'meteor', a: 1 }, { id: 'fire', a: 1 }], output: 'nova' },
  { inputs: [{ id: 'nova', a: 1 }, { id: 'void', a: 1 }], output: 'star' },
  { inputs: [{ id: 'golem', a: 1 }, { id: 'essence', a: 1 }], output: 'chimera' },
  // Batch 2: frost
  { inputs: [{ id: 'ice', a: 2 }], output: 'frost' },
  { inputs: [{ id: 'ice', a: 1 }, { id: 'dust', a: 1 }], output: 'frost' },
  // bubble
  { inputs: [{ id: 'water', a: 1 }, { id: 'life', a: 1 }], output: 'bubble' },
  { inputs: [{ id: 'mud', a: 1 }, { id: 'air', a: 1 }], output: 'bubble' },
  // echo
  { inputs: [{ id: 'air', a: 1 }, { id: 'mountain', a: 1 }], output: 'echo' },
  { inputs: [{ id: 'thunder', a: 1 }, { id: 'stone', a: 1 }], output: 'echo' },
  // vine
  { inputs: [{ id: 'wood', a: 1 }, { id: 'water', a: 1 }], output: 'vine' },
  { inputs: [{ id: 'life', a: 1 }, { id: 'wood', a: 1 }], output: 'vine' },
  // root
  { inputs: [{ id: 'earth', a: 1 }, { id: 'wood', a: 1 }], output: 'root' },
  { inputs: [{ id: 'earth', a: 1 }, { id: 'flower', a: 1 }], output: 'root' },
  // mushroom
  { inputs: [{ id: 'swamp', a: 1 }, { id: 'life', a: 1 }], output: 'mushroom' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'moss', a: 1 }], output: 'mushroom' },
  // seed
  { inputs: [{ id: 'flower', a: 1 }, { id: 'earth', a: 1 }], output: 'seed' },
  { inputs: [{ id: 'flower', a: 1 }, { id: 'death', a: 1 }], output: 'seed' },
  // gold
  { inputs: [{ id: 'metal', a: 1 }, { id: 'light', a: 1 }], output: 'gold' },
  { inputs: [{ id: 'metal', a: 1 }, { id: 'essence', a: 1 }], output: 'gold' },
  { inputs: [{ id: 'sun', a: 1 }, { id: 'metal', a: 1 }], output: 'gold' },
  // silver
  { inputs: [{ id: 'metal', a: 1 }, { id: 'lightning', a: 1 }], output: 'silver' },
  { inputs: [{ id: 'star', a: 1 }, { id: 'metal', a: 1 }], output: 'silver' },
  // iron
  { inputs: [{ id: 'earth', a: 1 }, { id: 'meteor', a: 1 }], output: 'iron' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'mountain', a: 1 }], output: 'iron' },
  // scroll
  { inputs: [{ id: 'wood', a: 1 }, { id: 'rune', a: 1 }], output: 'scroll' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'gold', a: 1 }], output: 'scroll' },
  // lantern
  { inputs: [{ id: 'glass', a: 1 }, { id: 'fire', a: 1 }], output: 'lantern' },
  { inputs: [{ id: 'iron', a: 1 }, { id: 'glass', a: 1 }], output: 'lantern' },
  // key
  { inputs: [{ id: 'metal', a: 1 }, { id: 'clockwork', a: 1 }], output: 'key' },
  { inputs: [{ id: 'gold', a: 1 }, { id: 'rune', a: 1 }], output: 'key' },
  // shield
  { inputs: [{ id: 'steel', a: 1 }, { id: 'earth', a: 1 }], output: 'shield' },
  { inputs: [{ id: 'iron', a: 1 }, { id: 'clay', a: 1 }], output: 'shield' },
  // wand
  { inputs: [{ id: 'wood', a: 1 }, { id: 'essence', a: 1 }], output: 'wand' },
  { inputs: [{ id: 'wood', a: 1 }, { id: 'crystal', a: 1 }], output: 'wand' },
  // curse
  { inputs: [{ id: 'shadow', a: 1 }, { id: 'poison', a: 1 }], output: 'curse' },
  { inputs: [{ id: 'death', a: 1 }, { id: 'essence', a: 1 }], output: 'curse' },
  // fairy
  { inputs: [{ id: 'life', a: 1 }, { id: 'light', a: 1 }], output: 'fairy' },
  { inputs: [{ id: 'flower', a: 1 }, { id: 'essence', a: 1 }], output: 'fairy' },
  // phantom
  { inputs: [{ id: 'ghost', a: 1 }, { id: 'shadow', a: 1 }], output: 'phantom' },
  { inputs: [{ id: 'ether', a: 1 }, { id: 'death', a: 1 }], output: 'phantom' },
  // moon
  { inputs: [{ id: 'star', a: 1 }, { id: 'shadow', a: 1 }], output: 'moon' },
  { inputs: [{ id: 'silver', a: 1 }, { id: 'void', a: 1 }], output: 'moon' },
  // sun
  { inputs: [{ id: 'star', a: 1 }, { id: 'fire', a: 1 }], output: 'sun' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'essence', a: 1 }], output: 'sun' },
  // galaxy
  { inputs: [{ id: 'star', a: 2 }], output: 'galaxy' },
  { inputs: [{ id: 'nova', a: 1 }, { id: 'ether', a: 1 }], output: 'galaxy' },
  // elixir
  { inputs: [{ id: 'potion', a: 1 }, { id: 'gold', a: 1 }], output: 'elixir' },
  { inputs: [{ id: 'water', a: 1 }, { id: 'essence', a: 1 }], output: 'elixir' },
  // catalyst
  { inputs: [{ id: 'essence', a: 1 }, { id: 'gold', a: 1 }], output: 'catalyst' },
  { inputs: [{ id: 'essence', a: 1 }, { id: 'fire', a: 1 }], output: 'catalyst' },
  // salt
  { inputs: [{ id: 'fire', a: 1 }, { id: 'water', a: 1 }, { id: 'earth', a: 1 }], output: 'salt' },
  { inputs: [{ id: 'fire', a: 1 }, { id: 'steam', a: 1 }], output: 'salt' },
  // Cross-recipes batch 2
  { inputs: [{ id: 'brick', a: 1 }, { id: 'clay', a: 1 }], output: 'ceramic' },
  { inputs: [{ id: 'ceramic', a: 1 }, { id: 'crystal', a: 1 }], output: 'crown' },
  { inputs: [{ id: 'crown', a: 1 }, { id: 'diamond', a: 1 }], output: 'amulet' },
  { inputs: [{ id: 'rust', a: 1 }, { id: 'salt', a: 1 }], output: 'metal' },
  { inputs: [{ id: 'blade', a: 1 }, { id: 'iron', a: 1 }], output: 'steel' },
  { inputs: [{ id: 'blade', a: 1 }, { id: 'gold', a: 1 }], output: 'key' },
  { inputs: [{ id: 'pearl', a: 1 }, { id: 'silver', a: 1 }], output: 'moon' },
  { inputs: [{ id: 'pearl', a: 1 }, { id: 'essence', a: 1 }], output: 'potion' },
  { inputs: [{ id: 'meteor', a: 1 }, { id: 'star', a: 1 }], output: 'galaxy' },
  { inputs: [{ id: 'nova', a: 1 }, { id: 'shadow', a: 1 }], output: 'eclipse' },
  { inputs: [{ id: 'nova', a: 1 }, { id: 'sun', a: 1 }], output: 'galaxy' },
  { inputs: [{ id: 'inferno', a: 1 }, { id: 'ice', a: 1 }], output: 'steam' },
  { inputs: [{ id: 'spring', a: 1 }, { id: 'stone', a: 1 }], output: 'geyser' },
  { inputs: [{ id: 'mountain', a: 1 }, { id: 'lightning', a: 1 }], output: 'diamond' },
  { inputs: [{ id: 'gale', a: 1 }, { id: 'water', a: 1 }], output: 'hurricane' },
  { inputs: [{ id: 'rift', a: 1 }, { id: 'galaxy', a: 1 }], output: 'abyss' },
  { inputs: [{ id: 'coral', a: 1 }, { id: 'life', a: 1 }], output: 'siren' },
  { inputs: [{ id: 'amber', a: 1 }, { id: 'life', a: 1 }], output: 'fossil' },
  { inputs: [{ id: 'thunder', a: 1 }, { id: 'gale', a: 1 }], output: 'storm' },
  { inputs: [{ id: 'diamond', a: 1 }, { id: 'gold', a: 1 }], output: 'crown' },
  { inputs: [{ id: 'clockwork', a: 1 }, { id: 'essence', a: 1 }], output: 'golem' },
  { inputs: [{ id: 'flower', a: 1 }, { id: 'shadow', a: 1 }], output: 'curse' },
  { inputs: [{ id: 'mountain', a: 1 }, { id: 'earth', a: 1 }], output: 'stone' },
];

export const VARIANTS = ['hotSteam', 'wetSteam', 'sludge', 'magma', 'scoria'];

export const ACHIEVEMENTS = [
  { id: 'firstMix',    name: '✨ Первое смешивание',    desc: 'Успешно смешать элементы',                          check: s => s.stats.mixCount >= 1 },
  { id: 'discover10',  name: '🔍 Первые шаги',           desc: 'Открыть 10 элементов',                             check: s => s.discovered.size >= 10 },
  { id: 'discover25',  name: '🧭 Исследователь',         desc: 'Открыть 25 элементов',                             check: s => s.discovered.size >= 25 },
  { id: 'discover40',  name: '📚 Эрудит',                desc: 'Открыть 40 элементов',                             check: s => s.discovered.size >= 40 },
  { id: 'discoverAll', name: '👑 Великий алхимик',      desc: 'Открыть все элементы',                           check: s => s.discovered.size >= ELEMENT_IDS.length },
  { id: 'recipes10',   name: '📜 Новичок',               desc: 'Найти 10 рецептов',                                check: s => s.foundRecipes.size >= 10 },
  { id: 'recipes25',   name: '📖 Подмастерье',           desc: 'Найти 25 рецептов',                                check: s => s.foundRecipes.size >= 25 },
  { id: 'recipes50',   name: '📕 Мастер',                desc: 'Найти 50 рецептов',                                check: s => s.foundRecipes.size >= 50 },
  { id: 'recipesAll',  name: '🏛 Архивариус',           desc: 'Найти все рецепты',                                check: s => s.foundRecipes.size >= RECIPES.length },
  { id: 'firstBoom',   name: '💥 Бум!',                  desc: 'Пережить первый взрыв',                            check: s => s.stats.explosionCount >= 1 },
  { id: 'boom10',      name: '☄️ Катастрофа',            desc: 'Пережить 10 взрывов',                              check: s => s.stats.explosionCount >= 10 },
  { id: 'fromAshes',   name: '🔥 Из пепла',              desc: 'Открыть элемент через взрыв',                      check: s => s.stats.discoveryFromExplosion >= 1 },
  { id: 'allVariants', name: '🔄 Вариативность',        desc: 'Создать все 5 элементов-вариантов',                check: s => VARIANTS.every(v => s.discovered.has(v)) },
  { id: 'chimera',     name: '🐉 Химера',                desc: 'Создать легендарную Химеру',                       check: s => s.discovered.has('chimera') },
  { id: 'massProd',    name: '🏭 Алхимическая фабрика',  desc: 'Создать 500 единиц элементов',                     check: s => s.stats.totalCreated >= 500 },
];

export function recipeKey(recipe) {
  return recipe.inputs.map(i => i.id + ':' + i.a).sort().join('+') + '->' + recipe.output;
}

export const SAVE_KEY = 'alchemic_save_v1';
export const TREE_MAX_DEPTH = 3;
export const CAT_ORDER = ['starter', 'state', 'nature', 'metal', 'artifact', 'magic', 'cosmos', 'alchemy', 'legendary'];
